steps:
  - name: 'python:3.11' 
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        export PYTHONPATH=. 
        pytest tests/

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'silver2gold-pipeline'
      - '--region=europe-west1'
      - '--source=.'
      - '--entry-point=data_aggregation_pipeline'
      - '--runtime=python311'
      - '--trigger-http'
      - '--memory=512MB'

options:
  logging: CLOUD_LOGGING_ONLY